theme: jekyll-theme-cayman
github:
  release_url: https://github.com/shan18/Topic-Based-Image-Captioning/releases/tag/v1.1
  publication_url: https://link.springer.com/article/10.1007/s13369-019-04262-2
